services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=${MONGODB_URI}
      - NODE_ENV=development
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECERET_ACCESS_KEY}
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  node_modules:
